### ISSUE TITLE
Resolutions hard to discover

### ISSUE THREAD

**Issue by nrnrnr** [any2cards/worldhaven#17]
I'd like to use these images to lay out an organizer for tiles.  To do so, I need to know the physical dimensions of each tile.  I could compute that from the image resolution, except resolutions seem to vary.  For example, the terrain tile `fh-cave-corridor-small.png` appears to have a resolution of 300 pixels per inch.  But the terrain tile `fh-cave-corridor-large.png` appears to have a resolution of around 230 pixels per inch.

Could the resolutions be made discoverable?  Or is that a fool's errand?

**Comment by any2cards** [comment]
The images stored within the Worldhaven repo have been manipulated to best serve the purpose of this repo ... that is the display of the images within the asset viewer.  This includes processing them through various tools to optimize their use for the viewer.  Originally, all of the hi-res unaltered versions of the assets were also stored within this repo, but had to be removed due to GitHub size limitations.  I am in the process of setting up a separate repo for sharing the unaltered high resolution versions of the images.  This will take some time.  If you send me an e-mail to any2cards@yahoo.com, I can provide you a temporary link, so that you can get all of the terrain images.
