### ISSUE TITLE
BGG's New Subscription Page is Broken w/ Extension Enabled

### ISSUE THREAD

**Issue by fifguy85** [any2cards/worldhaven#27]
With BGG's release of their new subscription page, I'm now getting a horribly mangled UI while having WAV enabled on the page. :(

![WAV On](https://github.com/any2cards/worldhaven/assets/25335488/af2b6021-0bbd-465b-900d-642d7e446581)
![WAV Off](https://github.com/any2cards/worldhaven/assets/25335488/c2c7ce75-11e6-4264-8e24-6d864409f103)

Chrome Version 119.0.6045.160 (Official Build) (64-bit)

**Comment by any2cards** [comment]
I know this isn't going to make you feel any better, but you are in good company.  Ever since BGG began their website more than 4+ years ago (but expecially in the past 2 years), various parts and pieces of it have caused never ending issues with my extension.

Unfortunately, I know enough to be dangerous when it comes to web design; and up until now, I have not been able to resolve any of the issues wrapped around the enigma known as BGG.  I have been trying to find a really, really good Web Designer that could assist me in resolving these issues; I didn't think this would be such a tough prospect, as the code itself is just a few files, and narrowing down the behavior and what is causing it SHOULD be simple.  It has, however, eluded me.

I am not going to be able to do anything about this until I can find someone that I can collaborate with to resolve these issues.  I am sorry !

**Comment by fifguy85** [comment]
Totally understand. I appreciate all the effort you've put into the tool and will keep using it (just needing to toggle more often :D). Good luck finding a web-dev to assist!!!

**Comment by any2cards** [comment]
Good news ... I have found an actual user of my extensions who was a programmer throughout his life (no retired).  He has offered to look at my code and see if he can resolve the issues.  We spent several hours working together tonight via phone so that I can explain how it all works.  He is now starting to debug various issues I have explained that the extension has.

**Comment by any2cards** [comment]
All issues with the WAV have been resolved with version 2.5.1.

**Comment by tomjudkins** [comment]
Hey, I'm glad you got this sorted... I've been slammed at work and trying to avoid screens at night
