### ISSUE TITLE
Revised ability cards for BT

### ISSUE THREAD

**Issue by Zachu** [any2cards/worldhaven#8]
Hey!

Is the main branch ability cards supposed to be the revised ones? I think in case of [BT](https://github.com/any2cards/worldhaven/tree/master/images/character-ability-cards/gloomhaven/BT) some cards are still the old ones. I would assume all of which were committed in 6c231a40fce1d83014a31316b3c1957cf57b7e91.

For example the file `gh-disorienting-roar` looks as in my edition in the earlier commit https://github.com/any2cards/worldhaven/blob/ef9910b12169f0668aecd6d83889b36a64705f6b/images/character-ability-cards/gloomhaven/BT/gh-disorienting-roar.png but this file https://github.com/any2cards/worldhaven/blob/00595c2ff8de650fb8a83c899a7c395a076387eb/images/character-ability-cards/gloomhaven/BT/gh-disorienting-roar.png is in the current main branch.

Same thing with `gh-spirit-swap` and I assume `gh-primal-blessing` but I haven't unlocked that one yet so can't confirm.

Or... Hmm... Is there really a newer version after my quite recently bought retail version? 😅

**Comment by any2cards** [comment]
Forgive me, as I am a bit confused as to what you are asking.  All of the assets in the main branch are the active, correct assets.  Note for the case of the Beast Tyrant, 3 of their cards were deprecated (the ones that use the word "Swap"), and were replaced/updated with cards (the ones that use the word "Teleport").  In order to provide people the ability to see both, depending on what version of the game they have, and what version of the cards they have, both exist within the repository.

You can see this effect in action by using the Worldhaven Card Viewer extension for Chrome or Firefox.  When you hover over Disorienting Roar for example, you will see the newest version of the card which includes the word Teleport. If you go to the Deprecated Assets section, you can see BOTH versions of the card side by side.

If this does not answer your question, let me know.

**Comment by Zachu** [comment]
Aargh I think you're absolutely right. I thought my physical Gloomhaven edition would have the latest edition of cards being bought quite recently. I was even more convinced by the fact that the "swap" version of the texts seemed much clearer and fine tuned that the latest "teleport" wording. I was absolutely convinced that the swap one has to be the latest one.

But I stand corrected and apparently that is not the case. The current main branch is up to date as it should be :) Sorry for bothering!
